Add middleware
AckeeCZ/crudella pull request #8
Opened 2019-01-07 13:10 UTC by grissius

2019-01-08 11:25 UTC, smoliji requested changes

2019-01-08 11:25 UTC, smoliji commented on src/lib/service/middleware.ts
> +            .route(`${resourceName}:${idName}`)
The `resourceName` must contain the trailing slash, otherwise slash is missing in `${resourceName}:${idName}`.

I find it weird to call it like this: `createMiddleware('/dalmatian/');`. Passing in just `dalmatian` is much more friendly. The middleware builder should then sanitize and format the name to contain the slashes if needed. non?

2019-01-08 11:25 UTC, smoliji commented on src/test/crudella.test.ts
> +let app: any;
Variable is used in `Middleware` suite only, so there is no need to have it module-global.

2019-01-08 13:25 UTC, smolijar commented on src/lib/service/middleware.ts
> +            .route(`${resourceName}:${idName}`)
Solved as composition of two routers, the starting slash seems necessery.

2019-01-08 13:25 UTC, smolijar commented on src/test/crudella.test.ts
> +let app: any;
Tru dat, fixed.

2019-01-09 07:30 UTC, smoliji approved these changes

2019-01-09 07:39 UTC, merged